### ISSUE TITLE
Remove hard-coding of a protocol name (http/https)

### ISSUE THREAD

**Issue by okayu9** [youichiro/gec-classifier#1]
Protocol name  (http/https) is specified by hard-coding in ajax.
https://github.com/youichiro/gec-classifier/blob/ebbb4475773cf7cb422976b62a0534ef97e28239/app.py#L19

Protocol name can be got like this:
https://stackoverflow.com/questions/14484288/is-it-possible-to-ajax-get-the-same-url-in-http-and-https?lq=1

**Comment by okayu9** [comment]
Or, it should be included in `$URL_PREFIX`.

**Comment by youichiro** [comment]
Done: https://github.com/youichiro/gec-classifier/commit/71dac6809fe15f08d351b670044d3c5246918177
